### ISSUE TITLE
Modelagem de dados

### ISSUE THREAD

**Issue by vigiaquinze** [vigiaquinze/gerenciamento-estoques-e-ativos-patrimoniais#1]

**Comment by ryangabriel27** [comment]
![Image](https://github.com/vigiaquinze/gerenciamento-estoques-e-ativos-patrimoniais/assets/123770312/93f4923c-fe8a-4f21-8861-3220bb3219be)

**Comment by ryangabriel27** [comment]
https://lucid.app/lucidchart/7a79b117-ff1d-4aaa-b48a-e33183c750b4/edit?viewport_loc=-42%2C-123%2C3050%2C1494%2C0_0&invitationId=inv_403faeae-6d02-4451-97af-30821bdd483c

**Comment by vigiaquinze** [comment]
![Image](https://github.com/vigiaquinze/gerenciamento-estoques-e-ativos-patrimoniais/assets/22718295/05f967b6-38a5-47ed-ab82-2ec2a4582e73)
